### ISSUE TITLE
Document signal handler logic.

### ISSUE THREAD

**Issue by vext01** [softdevteam/ykdocs#4]
In ykrustc, we have a trace invalidation scheme which signal handlers invoke.

I think we should document it.

**Comment by ltratt** [comment]
> In ykrustc, we have a trace invalidation scheme which signal handlers invoke.

I can't parse this: could you briefly expand what it means? I assume it means "if a signal occurs during [hardware? software?] tracing, then we must invalidate that trace"?

**Comment by vext01** [comment]
> I assume it means "if a signal occurs during [hardware? software?] tracing, then we must invalidate that trace"?

Correct. Exactly that.

Lukas is currently investigating what needs to be done for hardware traces.

Further reading:
 - https://github.com/softdevteam/ykrustc/blob/3e83bd2fb5877b5bfe4e443b6bcd42d69bfe2599/src/libcore/yk_swt.rs#L85
 - https://github.com/softdevteam/ykrustc/blob/3e83bd2fb5877b5bfe4e443b6bcd42d69bfe2599/src/libcore/yk_swt_impl.c#L124
 - https://github.com/softdevteam/ykrustc/blob/3e83bd2fb5877b5bfe4e443b6bcd42d69bfe2599/src/libstd/sys/unix/stack_overflow.rs#L88

Currently we set an atomic thread-local bool to false, which the code that stops tracing then looks at.

Ideally the flag would be inside one of our `ThreadTracer` structs, but it's not clear how: a) the signal handler should find the right `ThreadTracer`, or b) how it should access it in a reentrant manner.

With signal handlers, I like to err on the side of caution: I think we can live with setting a thread-local atomic bool and it's easy to see that it's also safe.

**Comment by ltratt** [comment]
> With signal handlers, I like to err on the side of caution: I think we can live with setting a thread-local atomic bool and it's easy to see that it's also safe.

Does "thread-local" and "signal handler" make sense? As you suggest above, if we've got several tracers ongoing then can we even tell which was interrupted? [I ask these questions out of pure ignorance rather than because I know the correct answer. Signals make my head hurt.]

**Comment by vext01** [comment]
I think you might be right. Something is fishy and we need to investigate.

When a signal arrives to a process, which thread(s) call the handler?

Will look into this.

**Comment by vext01** [comment]
```
#include <pthread.h>
#include <unistd.h>
#include <stdio.h>
#include <stdbool.h>
#include <stdint.h>
#include <inttypes.h>
#include <stdatomic.h>
#include <stdlib.h>
#include <signal.h>

#define N_THREADS   4

static __thread volatile atomic_bool tl = false;

static void
handler(int signo) {
    atomic_store_explicit(&tl, true, memory_order_relaxed);
}

void *
do_stuff(void *arg)
{
    uint64_t t = (uint64_t) arg;

	while (true) {
        bool b = atomic_load_explicit(&tl, memory_order_relaxed);
        printf("thread %" PRIu64 ": %d\n", t, b);
        sleep(2);
	}
}

int
main(void)
{
    pthread_t threads[N_THREADS];
    int err;
    uint64_t i;

    for (i = 0; i < N_THREADS; i++) {
        err = pthread_create(&threads[i], NULL, do_stuff, (void *) i);
        if (err) {
            printf("An error occured: %d", err);
            return 1;
        }
    }

    if (signal(SIGUSR1, handler) == SIG_ERR) {
        printf("register handler fail\n");
        exit(EXIT_FAILURE);
    }

    // blocks forever ofcourse.
    for (i = 0; i < N_THREADS; i++) {
        pthread_join(threads[i], NULL);
    }

    return 0;
}
```

 - OpenBSD: One thread has its thread local set after sending a SIGUSR1.
 - Linux: No thread-locals are set after sending a SIGUSR1.

**Comment by vext01** [comment]
https://unix.stackexchange.com/a/334308/21184

Linux:
> Signals generated for a process are delivered to only one thread. Thus, if more than one thread is eligible to receive a signal, one has to be chosen.

OpenBSD: 
> Signals handlers are normally run on the stack of the currently executing thread.

What I neglected to consider in my example above is that the supervising thread could also receive the signal.

Anyway, all of this means, our signal handler logic is wrong.

For now we should (as Laurie has suggested in MM) kill the VM with an error message and we can address this later.
